"""
rate_limiter.py — provider-aware rate limiting for OpportunityBot.

Tracks:
    - requests per minute (RPM)
    - requests per day (RPD)
    - tokens per minute (TPM)
    - tokens per day (TPD)

The limiter is intentionally conservative. Provider limits can be overridden
through environment variables without changing code.

IMPORTANT
---------
This limiter only tracks requests made by the current process/scan. It cannot
see usage generated by other applications, API keys, or previous processes.

If the provider itself returns HTTP 429, the caller should still treat that
provider as rate-limited for the remainder of the scan.
"""

import os
import time
from collections import defaultdict, deque
from threading import Lock


__all__ = [
    "wait_for_quota",
    "seconds_until_available",
    "DailyQuotaExceeded",
    "snapshot",
    "register_provider",
    "known_providers",
    "record_usage",
    "LIMITS",
]


# ═══════════════════════════════════════════════════════════════════════════
# EXCEPTIONS
# ═══════════════════════════════════════════════════════════════════════════


class DailyQuotaExceeded(Exception):
    """Raised when a provider's daily request/token budget is exhausted."""


class TokenQuotaExceeded(Exception):
    """Reserved for future explicit token-quota handling."""


# ═══════════════════════════════════════════════════════════════════════════
# LOCK
# ═══════════════════════════════════════════════════════════════════════════


_lock = Lock()


# ═══════════════════════════════════════════════════════════════════════════
# LIMITS
# ═══════════════════════════════════════════════════════════════════════════
#
# These defaults reflect the limits you provided from your provider consoles.
#
# Groq:
#   30 RPM
#   1,000 RPD
#   8,000 TPM
#   200,000 TPD
#
# Gemini:
#   15 RPM
#   1,500 RPD
#
# OpenRouter/Mistral remain conservative because their exact free limits can
# vary by account/model.
#
# All limits can be overridden through environment variables.
# ═══════════════════════════════════════════════════════════════════════════


LIMITS = {
    "claude": {
        "rpm": 999,
        "rpd": 999_999,
        "tpm": 999_999_999,
        "tpd": 999_999_999,
    },

    "gemini": {
        "rpm": int(
            os.getenv(
                "GEMINI_REQUESTS_PER_MINUTE",
                "15",
            )
        ),
        "rpd": int(
            os.getenv(
                "GEMINI_REQUESTS_PER_DAY",
                "1500",
            )
        ),
        "tpm": int(
            os.getenv(
                "GEMINI_TOKENS_PER_MINUTE",
                "1_000_000",
            )
        ),
        "tpd": int(
            os.getenv(
                "GEMINI_TOKENS_PER_DAY",
                "1_000_000_000",
            )
        ),
    },

    "groq": {
        "rpm": int(
            os.getenv(
                "GROQ_REQUESTS_PER_MINUTE",
                "30",
            )
        ),
        "rpd": int(
            os.getenv(
                "GROQ_REQUESTS_PER_DAY",
                "1000",
            )
        ),
        "tpm": int(
            os.getenv(
                "GROQ_TOKENS_PER_MINUTE",
                "8000",
            )
        ),
        "tpd": int(
            os.getenv(
                "GROQ_TOKENS_PER_DAY",
                "200000",
            )
        ),
    },

    "openrouter": {
        "rpm": int(
            os.getenv(
                "OPENROUTER_REQUESTS_PER_MINUTE",
                "20",
            )
        ),
        "rpd": int(
            os.getenv(
                "OPENROUTER_REQUESTS_PER_DAY",
                "1000",
            )
        ),
        "tpm": int(
            os.getenv(
                "OPENROUTER_TOKENS_PER_MINUTE",
                "8000",
            )
        ),
        "tpd": int(
            os.getenv(
                "OPENROUTER_TOKENS_PER_DAY",
                "200000",
            )
        ),
    },

    "mistral": {
        "rpm": int(
            os.getenv(
                "MISTRAL_REQUESTS_PER_MINUTE",
                "10",
            )
        ),
        "rpd": int(
            os.getenv(
                "MISTRAL_REQUESTS_PER_DAY",
                "500",
            )
        ),
        "tpm": int(
            os.getenv(
                "MISTRAL_TOKENS_PER_MINUTE",
                "8000",
            )
        ),
        "tpd": int(
            os.getenv(
                "MISTRAL_TOKENS_PER_DAY",
                "200000",
            )
        ),
    },

    "google": {
        "rpm": int(
            os.getenv(
                "GOOGLE_REQUESTS_PER_MINUTE",
                "10",
            )
        ),
        "rpd": int(
            os.getenv(
                "GOOGLE_REQUESTS_PER_DAY",
                "90",
            )
        ),
        "tpm": int(
            os.getenv(
                "GOOGLE_TOKENS_PER_MINUTE",
                "100000",
            )
        ),
        "tpd": int(
            os.getenv(
                "GOOGLE_TOKENS_PER_DAY",
                "1_000_000",
            )
        ),
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# USAGE HISTORY
# ═══════════════════════════════════════════════════════════════════════════
#
# Requests are stored as timestamps.
#
# Token usage is stored as:
#
#     (timestamp, token_count)
#
# This lets us calculate rolling one-minute and one-day token usage.
# ═══════════════════════════════════════════════════════════════════════════


_minute_history = defaultdict(
    deque,
    {
        name: deque()
        for name in LIMITS
    },
)


_day_history = defaultdict(
    deque,
    {
        name: deque()
        for name in LIMITS
    },
)


_minute_tokens = defaultdict(
    deque,
    {
        name: deque()
        for name in LIMITS
    },
)


_day_tokens = defaultdict(
    deque,
    {
        name: deque()
        for name in LIMITS
    },
)


# ═══════════════════════════════════════════════════════════════════════════
# PROVIDER REGISTRATION
# ═══════════════════════════════════════════════════════════════════════════


def register_provider(
    name: str,
    rpm: int,
    rpd: int,
    tpm: int = 999_999_999,
    tpd: int = 999_999_999,
) -> None:
    """
    Add or override a provider's limits at runtime.

    Existing usage history is preserved.
    """

    with _lock:
        LIMITS[name] = {
            "rpm": int(rpm),
            "rpd": int(rpd),
            "tpm": int(tpm),
            "tpd": int(tpd),
        }

        _minute_history[name]
        _day_history[name]
        _minute_tokens[name]
        _day_tokens[name]


def known_providers() -> list:
    """Return providers known to the limiter."""

    with _lock:
        return sorted(LIMITS)


# ═══════════════════════════════════════════════════════════════════════════
# CLEANUP
# ═══════════════════════════════════════════════════════════════════════════


def _cleanup_provider(
    model: str,
    now: float,
) -> None:
    """Remove usage entries outside their rolling windows."""

    minute_history = _minute_history[model]
    day_history = _day_history[model]

    minute_tokens = _minute_tokens[model]
    day_tokens = _day_tokens[model]

    minute_cutoff = now - 60
    day_cutoff = now - 86_400

    while (
        minute_history
        and minute_history[0] < minute_cutoff
    ):
        minute_history.popleft()

    while (
        day_history
        and day_history[0] < day_cutoff
    ):
        day_history.popleft()

    while (
        minute_tokens
        and minute_tokens[0][0] < minute_cutoff
    ):
        minute_tokens.popleft()

    while (
        day_tokens
        and day_tokens[0][0] < day_cutoff
    ):
        day_tokens.popleft()


def _token_total(history) -> int:
    """Return total tokens in a token-history deque."""

    return sum(
        tokens
        for _, tokens in history
    )


# ═══════════════════════════════════════════════════════════════════════════
# REQUEST QUOTA
# ═══════════════════════════════════════════════════════════════════════════


def wait_for_quota(model: str) -> None:
    """
    Block until a request is safe under request-rate limits.

    This function reserves a request slot.

    Token usage is checked using the currently-known token history, but the
    actual token usage is recorded later by record_usage() when the provider
    response is available.

    Raises DailyQuotaExceeded when the daily request limit is exhausted.
    """

    if model not in LIMITS:
        return

    while True:

        with _lock:

            now = time.time()

            limits = LIMITS[model]

            _cleanup_provider(
                model,
                now,
            )

            minute_history = _minute_history[model]
            day_history = _day_history[model]

            minute_tokens = _minute_tokens[model]
            day_tokens = _day_tokens[model]

            # ───────────────────────────────────────────────────────────
            # DAILY REQUEST LIMIT
            # ───────────────────────────────────────────────────────────

            if len(day_history) >= limits["rpd"]:
                raise DailyQuotaExceeded(
                    f"{model} daily request budget "
                    f"({limits['rpd']}) exhausted"
                )

            # ───────────────────────────────────────────────────────────
            # DAILY TOKEN LIMIT
            # ───────────────────────────────────────────────────────────

            day_token_total = _token_total(
                day_tokens
            )

            if (
                day_token_total
                >= limits["tpd"]
            ):
                raise DailyQuotaExceeded(
                    f"{model} daily token budget "
                    f"({limits['tpd']}) exhausted"
                )

            # ───────────────────────────────────────────────────────────
            # REQUESTS PER MINUTE
            # ───────────────────────────────────────────────────────────

            if (
                len(minute_history)
                >= limits["rpm"]
            ):

                wait = (
                    60
                    - (
                        now
                        - minute_history[0]
                    )
                    + 0.1
                )

            # ───────────────────────────────────────────────────────────
            # TOKEN PER MINUTE
            # ───────────────────────────────────────────────────────────

            elif (
                _token_total(
                    minute_tokens
                )
                >= limits["tpm"]
            ):

                wait = (
                    60
                    - (
                        now
                        - minute_tokens[0][0]
                    )
                    + 0.1
                )

            else:

                stamp = time.time()

                minute_history.append(
                    stamp
                )

                day_history.append(
                    stamp
                )

                return

        print(
            f"⏳ Rate limit reached for "
            f"{model}, waiting "
            f"{wait:.1f}s"
        )

        time.sleep(
            max(
                wait,
                0.1,
            )
        )


# ═══════════════════════════════════════════════════════════════════════════
# TOKEN USAGE RECORDING
# ═══════════════════════════════════════════════════════════════════════════


def record_usage(
    model: str,
    tokens: int,
) -> None:
    """
    Record actual provider token usage.

    ``tokens`` should normally be:

        input_tokens + output_tokens

    This is intentionally separate from wait_for_quota() because actual token
    usage is only known after the provider responds.
    """

    if model not in LIMITS:
        return

    try:
        tokens = int(tokens)
    except (
        TypeError,
        ValueError,
    ):
        tokens = 0

    if tokens <= 0:
        return

    now = time.time()

    with _lock:

        _cleanup_provider(
            model,
            now,
        )

        stamp = time.time()

        _minute_tokens[model].append(
            (
                stamp,
                tokens,
            )
        )

        _day_tokens[model].append(
            (
                stamp,
                tokens,
            )
        )


# ═══════════════════════════════════════════════════════════════════════════
# AVAILABILITY CHECK
# ═══════════════════════════════════════════════════════════════════════════


def seconds_until_available(
    model: str,
) -> float:
    """
    Return seconds until a provider can accept another request.

    Returns:

        0.0
            immediately available

        positive number
            wait required

        inf
            daily quota exhausted
    """

    if model not in LIMITS:
        return 0.0

    with _lock:

        now = time.time()

        limits = LIMITS[model]

        _cleanup_provider(
            model,
            now,
        )

        minute_history = _minute_history[model]
        day_history = _day_history[model]

        minute_tokens = _minute_tokens[model]
        day_tokens = _day_tokens[model]

        # Daily request quota.
        if len(day_history) >= limits["rpd"]:
            return float("inf")

        # Daily token quota.
        if (
            _token_total(day_tokens)
            >= limits["tpd"]
        ):
            return float("inf")

        waits = []

        # RPM.
        if (
            len(minute_history)
            >= limits["rpm"]
        ):
            waits.append(
                max(
                    0.0,
                    60
                    - (
                        now
                        - minute_history[0]
                    )
                    + 0.1,
                )
            )

        # TPM.
        if (
            _token_total(
                minute_tokens
            )
            >= limits["tpm"]
        ):
            waits.append(
                max(
                    0.0,
                    60
                    - (
                        now
                        - minute_tokens[0][0]
                    )
                    + 0.1,
                )
            )

        if not waits:
            return 0.0

        return max(waits)


# ═══════════════════════════════════════════════════════════════════════════
# SNAPSHOT
# ═══════════════════════════════════════════════════════════════════════════


def snapshot() -> dict:
    """
    Return current request/token usage for diagnostics.

    Example:

        {
            "groq": {
                "last_minute": 4,
                "rpm_limit": 30,
                "tokens_last_minute": 6200,
                "tpm_limit": 8000,
                "today": 20,
                "rpd_limit": 1000,
                "tokens_today": 18000,
                "tpd_limit": 200000,
            }
        }
    """

    now = time.time()

    out = {}

    with _lock:

        for model in LIMITS:

            _cleanup_provider(
                model,
                now,
            )

            minute = len(
                _minute_history[model]
            )

            day = len(
                _day_history[model]
            )

            minute_tokens = _token_total(
                _minute_tokens[model]
            )

            day_tokens = _token_total(
                _day_tokens[model]
            )

            limits = LIMITS[model]

            out[model] = {
                "last_minute": minute,
                "rpm_limit": limits["rpm"],

                "tokens_last_minute": (
                    minute_tokens
                ),
                "tpm_limit": limits["tpm"],

                "today": day,
                "rpd_limit": limits["rpd"],

                "tokens_today": (
                    day_tokens
                ),
                "tpd_limit": limits["tpd"],
            }

    return out
